
version: "2"

checks:
  similar-code:
    enabled: false

  identical-code:
    enabled: false

  argument-count:
    config:
      threshold: 10

  complex-logic:
    config:
      threshold: 50

  file-lines:
    config:
      threshold: 2000

  method-complexity:
    config:
      threshold: 50

  method-count:
    config:
      threshold: 50

  method-lines:
    config:
      threshold: 200

  return-statements:
    config:
      threshold: 5

plugins:
  bandit:
    enabled: true

  checkstyle:
    enabled: true
    config:
      file: "tools/checkstyle.xml"
    checks:
      com.puppycrawl.tools.checkstyle.checks.coding.OneStatementPerLineCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.SingleLineJavadocCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.AbbreviationAsWordInNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.whitespace.OperatorWrapCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.InterfaceTypeParameterNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.indentation.IndentationCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.coding.MissingSwitchDefaultCheck:
        enabled: false
      AnnotationLocationMostCases:
        enabled: false
      RightCurlyAlone:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck:
        enabled: false

  csslint:
    enabled: true

  editorconfig:
    enabled: true

  eslint:
    enabled: true

  fixme:
    enabled: true

  gofmt:
    enabled: true

  golint:
    enabled: true

  govet:
    enabled: true

  markdownlint:
    enabled: true

  nodesecurity:
    enabled: true

  pep8:
    enabled: true

  pmd:
    enabled: true

  radon:
    enabled: true

  sass-lint:
    enabled: true

  scss-lint:
    enabled: true

  sonar-java:
    enabled: true
    checks:
      squid:S3776:
        enabled: false
      squid:SwitchLastCaseIsDefaultCheck:
        enabled: false
      squid:S1214:
        enabled: false
      squid:S00115:
        enabled: false

  sonar-python:
    enabled: true

  stylelint:
    enabled: true

  swiftlint:
    enabled: true

  tailor:
    enabled: false

  tslint:
    enabled: true

exclude_patterns:
- "config/"
- "dist/"
- "node_modules/"
- "**/node_modules/"
- "**/test/"
- "**/tests/"
- "**/javatests/"
- "**/jstests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"

