##
# Copyright © 2020, The Gust Framework Authors. All rights reserved.
#
# The Gust/Elide framework and tools, and all associated source or object computer code, except where otherwise noted,
# are licensed under the Zero Prosperity license, which is enclosed in this repository, in the file LICENSE.txt. Use of
# this code in object or source form requires and implies consent and agreement to that license in principle and
# practice. Source or object code not listing this header, or unless specified otherwise, remain the property of
# Elide LLC and its suppliers, if any. The intellectual and technical concepts contained herein are proprietary to
# Elide LLC and its suppliers and may be covered by U.S. and Foreign Patents, or patents in process, and are protected
# by trade secret and copyright law. Dissemination of this information, or reproduction of this material, in any form,
# is strictly forbidden except in adherence with assigned license requirements.
##

steps:

# Build: Gust Framework
- name: 'us.gcr.io/elide-tools/tools/gcb'
  id: build
  args:
  - --bazelrc=.bazelrc
  - build
  - --config=ci
  - --config=release
  - --
  - //gust/...

# Image build: Todolist App
- name: 'us.gcr.io/elide-tools/tools/gcb'
  id: todolist
  args:
    - --bazelrc=.bazelrc
    - run
    - --config=ci
    - --config=release
    - --define=todolist_release_tag=$SHORT_SHA
    - --
    - //samples/todolist/src:TodolistServer-image-push

# Image pull: Built App
- name: 'gcr.io/cloud-builders/docker'
  id: pull
  args: ['pull', "us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA"]

# Image tag: Latest
- name: 'gcr.io/cloud-builders/docker'
  id: tag
  args: ['tag', 'us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA', 'us.gcr.io/elide-tools/sample/todolist/jvm:latest']

# Image push: Latest
- name: 'gcr.io/cloud-builders/docker'
  id: push
  args: ['push', 'us.gcr.io/elide-tools/sample/todolist/jvm:latest']

# Credentials: K8S
- name: 'gcr.io/cloud-builders/gcloud'
  id: cluster
  args: [
    'container',
    'clusters',
    'get-credentials',
    'k9-v4c',
    '--zone',
    'us-west2-c',
    '--project',
    'bloom-sandbox'
  ]

# Deploy: K8S (Envoy)
- name: 'us.gcr.io/elide-tools/tools/gcb'
  id: deploy-envoy
  args:
    - --bazelrc=.bazelrc
    - run
    - --config=ci
    - --
    - //samples/todolist/src/config:envoy.replace

# Deploy: K8S (Todolist)
- name: 'us.gcr.io/elide-tools/tools/gcb'
  id: deploy-todolist
  args:
    - --bazelrc=.bazelrc
    - run
    - --config=ci
    - --
    - //samples/todolist/src/config:todolist.replace

images:
  - us.gcr.io/elide-tools/sample/todolist/jvm:$SHORT_SHA
  - us.gcr.io/elide-tools/sample/todolist/jvm:latest

tags: ['framework', 'tools', 'gust']

timeout: 10m
options:
  machineType: "N1_HIGHCPU_8"
  sourceProvenanceHash: ['SHA256']
